### ISSUE TITLE
Random Crashing Solution

### ISSUE THREAD

**Issue by ThatDevExotic** [leia-uwu/survev#124]
`{"msg":"Uncaught TypeError: Cannot use 'in' operator to search for 'anim' in undefined","id":"c4bdcc9da49db019","url":"https://survev.io/js/app-B-X0DLuc.js","line":12758`

**The stacktrace for random crashing mid-game.**

**I didn't bother to look through the source, but for the built client replace**

`return this.downed ? t = "downed" : "anim" in e && e.anim.idlePose ? t = e.anim.idlePose : e.type == "gun" ? e.pistol ? t = e.isDual ? "dualPistol" : "pistol" : e.isBullpup ? t = "bullpup" : e.isLauncher ? t = "launcher" : t = e.isDual ? "dualRifle" : "rifle" : e.type == "throwable" ? t = "throwable" : t = "fists";`

**with** 

`return this.downed ? t = "downed" : (e && e.anim && e.anim.idlePose) ? t = e.anim.idlePose : e.type == "gun" ? e.pistol ? t = e.isDual ? "dualPistol" : "pistol" : e.isBullpup ? t = "bullpup" : e.isLauncher ? t = "launcher" : t = e.isDual ? "dualRifle" : "rifle" : e.type == "throwable" ? t = "throwable" : t = "fists";`

**Comment by leia-uwu** [comment]
that will just make the crash go elsewhere (i already tried it before)
the issue is that the active weapon is invalid
